### ISSUE TITLE
Unable to reference native library

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#350]
Flubu is having problem loading LibGit2Sharp.NativeBinaries package(https://github.com/libgit2/libgit2sharp.nativebinaries) which contains compiled versions of the libgit2 native library. Well it has problem loading any native library not only from libgit2. 

> ScriptError:CS0009: Metadata file 'D:\_GitFlubu\FlubuSample\flubucore-versionize-sample\BuildScript\FlubuLib\git2-106a5f2.dll' could not be opened -- PE image doesn't contain managed metadata.
Unhandled exception. FlubuCore.Scripting.ScriptLoaderExcetpion: Csharp source code file: BuildScript/BuildScript.cs has some compilation errors!
   at FlubuCore.Scripting.ScriptLoader.CompileBuildScript(String buildScriptAssemblyPath, String buildScriptFilePath, IEnumerable`1 references, String code) in c:\jenkins\workspace\FlubuCore\src\FlubuCore\Scripting\ScriptLoader.cs:line 250
   at FlubuCore.Scripting.ScriptLoader.FindAndCreateBuildScriptInstanceAsync(CommandArguments args) in c:\jenkins\workspace\FlubuCore\src\FlubuCore\Scripting\ScriptLoader.cs:line 124
   at FlubuCore.Scripting.ScriptProvider.GetBuildScriptAsync(CommandArguments commandArguments, Boolean forceReload) in c:\jenkins\workspace\FlubuCore\src\FlubuCore\Scripting\ScriptProvider.cs:line 26
   at DotNet.Cli.Flubu.Program.FlubuStartup(String[] args) in c:\jenkins\workspace\FlubuCore\src\dotnet-flubu\Program.cs:line 84
   at DotNet.Cli.Flubu.Program.Main(String[] args) in c:\jenkins\workspace\FlubuCore\src\dotnet-flubu\Program.cs:line 36
   at FlubuCore.Tool.Program.Main(String[] args) in c:\jenkins\workspace\FlubuCore\src\FlubuCore.Tool\Program.cs:line 9
   at FlubuCore.Tool.Program.<Main>(String[] args)

**Comment by mzorec** [comment]
@sreejith-ms I have found out that native library has to be in same directory as the library that has dependecy on it. I have made pull request to your  sample script repository https://github.com/sreejith-ms/flubucore-versionize-sample where I have put libgit2sharp.dll and libgit2sharp.native.dll to the same lib folder and add reference to libgit2sharp.dll in project file.

I am still not sure how to fix this when adding libgit2sharp with nuget package as libraries are not in the same nuget folder and also both libraries must not be added as references in project file or more exactly referenced when compiling the script.

**Comment by sreejith-ms** [comment]
@mzorec I have faced a [DLL not found issue](https://github.com/libgit2/libgit2sharp/issues/1798) when I run BuildScript in a CI system. But it is fixed when I updated libgit2sharp to the preview version as per this [issue](https://github.com/libgit2/libgit2sharp/issues/1703).
So the native library issue only occurring to libgit2sharp or do you able to test any other packages?

**Comment by mzorec** [comment]
I haven't tested it on other packages. I will try with one other package when I have time. It might libgit2sharp specific issue.

**Comment by mzorec** [comment]
Looks like libgit2sharp specific issue.
